# Generated by Django 2.2.10 on 2021-01-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycomics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('xpath', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'websites',
            },
        ),
        migrations.AlterModelTable(
            name='comicstrip',
            table='comicstrips',
        ),
    ]
