# Generated by Django 2.2.10 on 2021-01-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycomics', '0002_auto_20210119_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
